variable "resource-group-name" {}
variable "location" {}
variable "vnet-name" {}
variable "subnet-name" {}
variable "nsg-name" {}
variable "vm-name" {}
variable "admin-username" {}
variable "admin-password" {}
variable "vm-size" {}